document.addEventListener("DOMContentLoaded",()=>{
const data=[
{id:"ailife",image:"1.jpg",category:"AI情報発信",name:"あいらいふ",result:"1か月で150万閲覧・4,500フォロワー",goal:"AI情報を多くの人へ届け、認知を広げる",action:"診断型・参加型コンテンツを継続発信",outcome:"開設1か月で150万閲覧、4,500フォロワーを達成",summary:"企画の入口を『自分ごと化』し、保存・コメントしたくなる体験型の投稿へ。",analysis:["自分の結果を知りたくなる診断テーマを選定","冒頭1秒で完成イメージと参加メリットを提示","問いかけで視聴後のコメント行動まで設計"],changes:["一方的なAI解説から参加型企画へ変更","結論が一目で伝わるサムネイルへ整理","反応の良い企画をシリーズ化"]},
{id:"otaku",image:"2.jpg",category:"AI動画販売",name:"AIオタク",result:"動画の作り方を販売・月収100万円",goal:"AIのおもしろ動画を仕事につなげる",action:"再現動画を発信し、作り方を商品化",outcome:"動画制作ノウハウの販売で月収100万円を達成",summary:"再生だけで終えず、視聴者が欲しい『作り方』まで商品として設計。",analysis:["完成動画の驚きを最初の数秒で提示","再現方法を知りたい視聴者ニーズを把握","商品購入までの導線をプロフィールに集約"],changes:["作品紹介に制作過程を追加","反応の高い動画を教材化","企画が変わっても見せ方と導線を統一"]},
{id:"tete",image:"3.jpg",category:"ショップ集客",name:"&tete",result:"TikTok参入2か月目・売上50万円UP",goal:"子供服と木製おもちゃの魅力を届ける",action:"商品と日常が伝わる短尺動画を投稿",outcome:"参入2か月目で売上が50万円増加",summary:"商品の説明より、使う場面や温度感が伝わる世界観を重視。",analysis:["購入後の暮らしが想像できる使用シーンを重視","育児中の保護者が共感する日常の文脈","ショップへ迷わず移動できる導線"],changes:["商品単体から子どもの使用場面中心へ変更","色味・字幕・音楽を統一","売り込みを減らし共感から商品発見へ誘導"]},
{id:"bic",image:"4.jpg",category:"芸人・認知拡大",name:"びっく",result:"エンタメ動画・総再生1,000万回以上",goal:"お笑い芸人としての認知を広げる",action:"短い言葉と表情で伝わるエンタメを継続",outcome:"総再生数1,000万回以上を達成",summary:"一目で内容が伝わる画面と、繰り返し見たくなる型をシリーズ化。",analysis:["無音でも分かる大きなテロップと表情","短尺でオチまで到達する構成","同じ入り口の反復で人物と企画を記憶"],changes:["説明を削り冒頭から決め台詞へ","画角と字幕位置を固定","単発ではなく次も期待できる型を継続"]},
{id:"amista",image:"5.jpg",category:"スポーツ・認知＋収益",name:"FCアミスタ",result:"2,000万回over・認知＋動画収益",goal:"YouTube活動とチームの認知を広げる",action:"サッカーの検証・ドッキリをTikTok向けに最適化",outcome:"再生数2,000万回超、Creator Rewards Programでも収益化",summary:"YouTubeとは違う速い入口を作り、チームの魅力を短尺で届けました。",analysis:["結果が気になる検証テーマで視聴維持を獲得","複数メンバーの反応で個性も訴求","YouTube企画をTikTokの尺へ再編集"],changes:["長い前置きをなくし内容を冒頭で明示","カット間隔を短くし離脱を抑制","長尺視聴と収益条件も意識して構成"]},
{id:"yurukura",image:"6.jpg",category:"ASMR・収益化",name:"ゆるくら",result:"開設1か月・楽天ROOM＋動画で収益化",goal:"好きなシールとASMRを収益へつなげる",action:"手元の気持ちよさとコレクション性を映像化",outcome:"開設1か月で楽天ROOMと動画収益化を達成",summary:"顔出しなしでも、音・手元・世界観で見続けたくなる投稿を構築。",analysis:["音・手元・質感で滞在時間を伸ばした","集める楽しさで保存と再視聴を促進","動画の商品と楽天ROOMを自然に連動"],changes:["手元中心の撮影スタイルを確立","素材音が伝わる収録へ改善","紹介商品を固定テーマ化"]},
{id:"sauna",image:"7.jpg",category:"店舗・認知拡大",name:"真大阪サウナ",result:"動画で認知拡大・月間売上50万円以上UP",goal:"施設の存在と体験価値を地域へ届ける",action:"特徴的な空間と体験を短尺で見せる",outcome:"月間売上が50万円以上増加",summary:"設備紹介だけでなく『ここでしかできない体験』を冒頭から可視化。",analysis:["特徴的な設備をフックに採用","暗さ・光・音で来店前の体験を可視化","地域名と施設ジャンルがすぐ分かる設計"],changes:["設備一覧から体験を追う構成へ変更","意外性のある空間を冒頭に配置","認知動画と来店検討動画の役割を分離"]}
];
const slider=document.querySelector("#caseSlider");slider.innerHTML=data.map((x,i)=>`<button class="case-card" data-id="${x.id}"><figure><img src="tiktok-case-${x.image}" alt="${x.name}のTikTok実績" loading="lazy"><span>CASE ${String(i+1).padStart(2,"0")}</span></figure><div><small>${x.category}</small><h3>${x.name}</h3><strong>${x.result}</strong><em>分析を見る →</em></div></button>`).join("");
const step=()=>Math.min(380,slider.clientWidth*.86);let timer;const move=d=>{const end=slider.scrollWidth-slider.clientWidth;if(d>0&&slider.scrollLeft>=end-12)slider.scrollTo({left:0,behavior:"smooth"});else slider.scrollBy({left:d*step(),behavior:"smooth"})};const pause=()=>clearInterval(timer);const play=()=>{pause();timer=setInterval(()=>move(1),4200)};
document.querySelector(".arrow.prev").onclick=()=>{move(-1);play()};document.querySelector(".arrow.next").onclick=()=>{move(1);play()};["pointerdown","mouseenter"].forEach(e=>slider.addEventListener(e,pause,{passive:true}));["pointerup","pointercancel","mouseleave"].forEach(e=>slider.addEventListener(e,play,{passive:true}));document.addEventListener("visibilitychange",()=>document.hidden?pause():play());play();
const bar=document.querySelector(".progress span");slider.addEventListener("scroll",()=>{const m=slider.scrollWidth-slider.clientWidth;bar.style.transform=`translateX(${m?slider.scrollLeft/m*420:0}%)`},{passive:true});
const dialog=document.querySelector("#caseDialog"),set=(s,v)=>dialog.querySelector(s).textContent=v,list=(s,a)=>dialog.querySelector(s).innerHTML=a.map(v=>`<li>${v}</li>`).join("");document.querySelectorAll(".case-card").forEach(card=>card.onclick=()=>{const x=data.find(v=>v.id===card.dataset.id);pause();dialog.querySelector("img").src=`tiktok-case-${x.image}`;set(".dialog-category",x.category);set(".dialog-name",x.name);set(".dialog-result",x.result);set(".dialog-goal",x.goal);set(".dialog-action",x.action);set(".dialog-outcome",x.outcome);set(".dialog-summary",x.summary);list(".dialog-analysis",x.analysis);list(".dialog-changes",x.changes);dialog.showModal()});const close=()=>{dialog.close();play()};dialog.querySelector(".close").onclick=close;dialog.onclick=e=>{if(e.target===dialog)close()};
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll(".case-card,.viral figure,.process li,.cta-card").forEach(x=>reveal.observe(x));const floating=document.querySelector("#floating"),final=document.querySelector(".cta-card");new IntersectionObserver(([e])=>floating.classList.toggle("hide",e.isIntersecting),{threshold:.15}).observe(final);
});
