document.addEventListener("DOMContentLoaded",()=>{const data=[
{id:"ailife",image:"1.jpg",category:"AI情報発信",name:"あいらいふ",result:"1か月で150万閲覧・4,500フォロワー",goal:"AI情報を多くの人へ届け、認知を広げる",action:"診断型・参加型コンテンツを継続発信",outcome:"開設1か月で150万閲覧、4,500フォロワーを達成",summary:"企画の入口を『自分ごと化』し、保存・コメントしたくなる体験型の投稿へ。"},
{id:"otaku",image:"2.jpg",category:"AI動画販売",name:"AIオタク",result:"動画の作り方を販売・月収100万円",goal:"AIのおもしろ動画を仕事につなげる",action:"再現動画を発信し、作り方を商品化",outcome:"動画制作ノウハウの販売で月収100万円を達成",summary:"再生だけで終えず、視聴者が欲しい『作り方』まで商品として設計。"},
{id:"tete",image:"3.jpg",category:"ショップ集客",name:"&tete",result:"TikTok参入2か月目・売上50万円UP",goal:"子供服と木製おもちゃの魅力を届ける",action:"商品と日常が伝わる短尺動画を投稿",outcome:"参入2か月目で売上が50万円増加",summary:"商品の説明より、使う場面や温度感が伝わる世界観を重視。"},
{id:"bic",image:"4.jpg",category:"芸人・認知拡大",name:"びっく",result:"エンタメ動画・総再生1,000万回以上",goal:"お笑い芸人としての認知を広げる",action:"短い言葉と表情で伝わるエンタメを継続",outcome:"総再生数1,000万回以上を達成",summary:"一目で内容が伝わる画面と、繰り返し見たくなる型をシリーズ化。"},
{id:"amista",image:"5.jpg",category:"スポーツ・認知＋収益",name:"FCアミスタ",result:"2,000万回over・認知＋動画収益",goal:"YouTube活動とチームの認知を広げる",action:"サッカーの検証・ドッキリをTikTok向けに最適化",outcome:"再生数2,000万回超、Creator Rewards Programでも収益化",summary:"YouTubeとは違う速い入口を作り、チームの魅力を短尺で届けました。"},
{id:"yurukura",image:"6.jpg",category:"ASMR・収益化",name:"ゆるくら",result:"開設1か月・楽天ROOM＋動画で収益化",goal:"好きなシールとASMRを収益へつなげる",action:"手元の気持ちよさとコレクション性を映像化",outcome:"開設1か月で楽天ROOMと動画収益化を達成",summary:"顔出しなしでも、音・手元・世界観で見続けたくなる投稿を構築。"},
{id:"sauna",image:"7.jpg",category:"店舗・認知拡大",name:"真大阪サウナ",result:"動画で認知拡大・月間売上50万円以上UP",goal:"施設の存在と体験価値を地域へ届ける",action:"特徴的な空間と体験を短尺で見せる",outcome:"月間売上が50万円以上増加",summary:"設備紹介だけでなく『ここでしかできない体験』を冒頭から可視化。"}];
const slider=document.querySelector("#caseSlider");slider.innerHTML=data.map((x,i)=>`<button class="case-card" data-id="${x.id}"><figure><img src="tiktok-case-${x.image}" alt="${x.name}のTikTok実績" loading="lazy"><span>CASE ${String(i+1).padStart(2,"0")}</span></figure><div><small>${x.category}</small><h3>${x.name}</h3><strong>${x.result}</strong><em>詳しく見る →</em></div></button>`).join("");
document.querySelector(".arrow.prev").onclick=()=>slider.scrollBy({left:-380,behavior:"smooth"});document.querySelector(".arrow.next").onclick=()=>slider.scrollBy({left:380,behavior:"smooth"});const bar=document.querySelector(".progress span");slider.addEventListener("scroll",()=>{const m=slider.scrollWidth-slider.clientWidth;bar.style.transform=`translateX(${m?slider.scrollLeft/m*420:0}%)`},{passive:true});
const dialog=document.querySelector("#caseDialog");const set=(s,v)=>dialog.querySelector(s).textContent=v;document.querySelectorAll(".case-card").forEach(card=>card.onclick=()=>{const x=data.find(v=>v.id===card.dataset.id);dialog.querySelector("img").src=`tiktok-case-${x.image}`;set(".dialog-category",x.category);set(".dialog-name",x.name);set(".dialog-result",x.result);set(".dialog-goal",x.goal);set(".dialog-action",x.action);set(".dialog-outcome",x.outcome);set(".dialog-summary",x.summary);dialog.showModal()});dialog.querySelector(".close").onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll(".case-card,.viral figure,.process li,.cta-card").forEach(x=>reveal.observe(x));const floating=document.querySelector("#floating"),final=document.querySelector(".cta-card");new IntersectionObserver(([e])=>floating.classList.toggle("hide",e.isIntersecting),{threshold:.15}).observe(final);
});
